name: CI on Windows

on: [push,pull_request]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.0'
    - name: Run the default task
      run: |
        pacman -Syyu --noconfirm
        cmake --version
        ridk exec bundle install
        ridk exec bundle exec rake
